# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SQL_FMDB' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SQL_FMDB

  target 'SQL_FMDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SQL_FMDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry'
pod 'FMDB'

end
