# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '搜索栏界面搭建' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 搜索栏界面搭建
pod 'Masonry'


end
