# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '毛玻璃特效' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 毛玻璃特效

pod 'Masonry'
pod 'YYWebImage'
end
