# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JS与OC交互(WKWebView)' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JS与OC交互(WKWebView)
pod 'Masonry'
pod 'JSExtension'
end
