# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target '轮播器demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for 轮播器demo

pod 'Masonry'
pod 'YYWebImage'


end
